### ISSUE TITLE
can't use lua-releng with find command recursively

### ISSUE THREAD

**Issue by xiangnanscu** [openresty/openresty-devel-utils#13]
I have a folder named `lualib`, when cd that folder, I run `find . -name '*.lua' | lua-releng -s -e -L`, `lua-releng ` won't check files in subfolder such as `lualib/db/mysql.lua`. I know this because I set some global variables in subfolder on purpose. Am I wrong? Or what's the right way if I want to recursively check all lua files in some folder?

**Comment by agentzh** [comment]
@xiangnanscu Maybe you want to use the `-exec` option of `find` instead? `lua-releng` only supports a single individual file argument or no arguments at all (in which case it searchs `lib/`).

**Comment by xiangnanscu** [comment]
@agentzh thanks, chun ge.
