### ISSUE TITLE
lua-releng:  5.1 version luac treat bit module as global variable

### ISSUE THREAD

**Issue by Gerrard-YNWA** [openresty/openresty-devel-utils#18]
minimal case
```
local band = bit.band
```
lua-releng use 5.1 version luac interperter 
```
lua-releng test.lua 
Checking use of Lua global variables in file test.lua...
	op no.	line	instruction	args	; code
	1	[1]	GETGLOBAL	0 -1	; bit
```
should we need to ignore this?

**Comment by agentzh** [comment]
@Gerrard-YNWA Fixed in the lj-releng tool. It's not right to ignore `bit` in lua-releng since it is not a standard module in Lua 5.1 :)
