### ISSUE TITLE
ngx-build and missing patches (unsupported nginx versions)

### ISSUE THREAD

**Issue by chipitsine** [openresty/openresty-devel-utils#7]
when I use ngx-build with nginx-1.10, I see errors on missing patches

https://travis-ci.org/chipitsine/replace-filter-nginx-module

however, I still can compile nginx-1.10 with that module using --add-module

I think, if those patches are important, it should fail if I compile nginx with --add-module
and, if it acceptible, so ngx-build should not fail if there's no certain patch

**Comment by agentzh** [comment]
@chipitsine Well, OpenResty's nginx patches do not account for every single nginx release out there. Instead, we only prepare patches for nginx cores that have been or will be included in the official OpenResty bundle releases. This is to reduce our maintainence work, obviously. Future OpenResty releases will jump over the whole 1.10.x series since we only track nginx mainline releases.

**Comment by chipitsine** [comment]
people sometimes install stable version of nginx. and they might think "ok, there're tests, so definetily it is tested"

but, actually only mainline version is tested


so, we can expand test matrix to support stable version as well, but I'd suggest to change ngx-build behaviour like "if there's no patch, do not fail"

**Comment by agentzh** [comment]
@chipitsine Actually when the patches are missing, I do hope it fails early. Otherwise we'll see failures much later as test failures which can be much more subtle to analyze and understand.

**Comment by agentzh** [comment]
@chipitsine NGINX's stable versions just mean their C APIs are "stable" instead of their code quality. So it's usually true that if a newer mainline version passes the tests then must the previous "stable" versions, otherwise it would be NGINX's big problems (not us).

**Comment by agentzh** [comment]
@chipitsine The biggest problem is that we do not have enough resources to maintain patches for every single nginx release. That requires a lot more work. So we have to focus on the nginx core versions actually contained in an OpenResty release. Skipping patches in ngx-build do not solve the problems but often just hide the problems. You've already seen cases where some tests in the test suites are actually exercising the changes of OpenResty's nginx core patches.
